version: '3.8'

services:
  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - '27017:27017'

  app:
    build: .
    container_name: node-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb